// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend_loyalty.Data;

#nullable disable

namespace backend_loyalty.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend_loyalty.Model.LoyaltyAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<long>("PointsBalance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("points_balance");

                    b.Property<int>("Tier")
                        .HasColumnType("integer")
                        .HasColumnName("tier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_loyalty_accounts_created_at");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("idx_loyalty_accounts_is_active");

                    b.HasIndex("Tier")
                        .HasDatabaseName("idx_loyalty_accounts_tier");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("idx_loyalty_accounts_user_id");

                    b.ToTable("loyalty_accounts", (string)null);
                });

            modelBuilder.Entity("backend_loyalty.Model.LoyaltyRedemption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LoyaltyAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("loyalty_account_id");

                    b.Property<long>("PointsUsed")
                        .HasColumnType("bigint")
                        .HasColumnName("points_used");

                    b.Property<string>("RewardMetadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("reward_metadata");

                    b.Property<string>("RewardType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reward_type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_loyalty_redemptions_created_at");

                    b.HasIndex("LoyaltyAccountId")
                        .HasDatabaseName("idx_loyalty_redemptions_account_id");

                    b.HasIndex("RewardType")
                        .HasDatabaseName("idx_loyalty_redemptions_reward_type");

                    b.ToTable("loyalty_redemptions", (string)null);
                });

            modelBuilder.Entity("backend_loyalty.Model.LoyaltyTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ChangeAmount")
                        .HasColumnType("bigint")
                        .HasColumnName("change_amount");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LoyaltyAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("loyalty_account_id");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("metadata");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("reason");

                    b.Property<Guid?>("ReferenceId")
                        .HasColumnType("uuid")
                        .HasColumnName("reference_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("idx_loyalty_transactions_created_at");

                    b.HasIndex("LoyaltyAccountId")
                        .HasDatabaseName("idx_loyalty_transactions_account_id");

                    b.HasIndex("ReferenceId")
                        .HasDatabaseName("idx_loyalty_transactions_reference_id");

                    b.ToTable("loyalty_transactions", (string)null);
                });

            modelBuilder.Entity("backend_loyalty.Model.LoyaltyRedemption", b =>
                {
                    b.HasOne("backend_loyalty.Model.LoyaltyAccount", "LoyaltyAccount")
                        .WithMany("LoyaltyRedemptions")
                        .HasForeignKey("LoyaltyAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoyaltyAccount");
                });

            modelBuilder.Entity("backend_loyalty.Model.LoyaltyTransaction", b =>
                {
                    b.HasOne("backend_loyalty.Model.LoyaltyAccount", "LoyaltyAccount")
                        .WithMany("LoyaltyTransactions")
                        .HasForeignKey("LoyaltyAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoyaltyAccount");
                });

            modelBuilder.Entity("backend_loyalty.Model.LoyaltyAccount", b =>
                {
                    b.Navigation("LoyaltyRedemptions");

                    b.Navigation("LoyaltyTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
